### ISSUE TITLE
Melhorias para barra em telas com resolução abaixo de 900px

### ISSUE THREAD

**Issue by valessiobrito** [govbr/brasil.gov.barra#4]
Avaliar pull request:  https://github.com/govbr/brasil.gov.barra/pull/3

Histórico do desenvolvimento dessa Issue esta em  https://github.com/plonegovbr/brasil.gov.barra/issues/17

**Comment by caduvieira** [comment]
@valessiobrito  Merge realizado. Obrigado pela contribuição!
